import React from 'react';
import NavBar from './components/NavBar'; // Import your custom navigation component
import Layout from './components/Laoyout'; // Import your custom navigation component
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Add your head content here */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <NavBar /> {/* Render your custom navigation component */}
        <Layout>
        {children} {/* Render the children components */}
        </Layout>
      </body>
    </html>
  );
};

export default RootLayout;
