import React from 'react';
import NavBar from './components/NavBar'; // Import your custom navigation component
import { Inter } from "next/font/google";
import { ThemeProvider, CssBaseline } from '@mui/material'; // Import ThemeProvider and CssBaseline
import { createTheme } from '@mui/material/styles'; // Import createTheme
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Define your theme
const theme = createTheme({
  typography: {
    fontFamily: '"Roboto", "Arial", sans-serif',
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    // Add other typography defaults as needed
  },
  // Add other theme configurations as needed
});

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline /> {/* Apply baseline styles */}
      <html lang="en">
        <head>
          {/* Add your head content here */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
        </head>
        <body className={inter.className}>
          <NavBar /> {/* Render your custom navigation component */}
          {children} {/* Render the children components */}
        </body>
      </html>
    </ThemeProvider>
  );
};

export default RootLayout;

// Export metadata separately or handle it differently
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
