"use client"
import React from 'react';
import NavBar from './components/NavBar'; // Import your custom navigation component
import Layout from './components/Layout'; // Import your custom navigation component
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <NavBar /> {/* Render your custom navigation component */}
        <Layout>
        {children} {/* Render the children components */}
        </Layout>
      </body>
    </html>
  );
};

export default RootLayout;
